name: Push Docker Image on Code Change

on: 
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO: node_app

jobs: 
  push:
    name: Push docker image   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Authenticate to AWS 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION  }}

      - name: Authenticate to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 616864133429.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Generate docker image tag
        run: echo "TAG=${{ github.run_id }}.${{ github.run_number }}.${{ github.retention_days  }}" >> $GITHUB_ENV

      - name: build docker image
        run: docker build -t web:${{ env.TAG }} .

      - name: Run trivy scanning
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: web:${{ env.TAG }}
          type: sarif
          output: trivy-result.sarif 

      - name: Send File To Github
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-result.sarif'

      - name: Tag docker image
        run: docker tag  web:${{env.TAG }} 616864133429.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPO }}:${{ env.TAG  }}

      - name: Push docker image to ECR
        run: docker push 616864133429.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPO }}:${{ env.TAG  }}

  deploy:
    name: Pull docker image
    runs-on: ubuntu-latest
    needs: push 

    steps:
      - name: Setup sevrer
        uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
        with:
          privateKey: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          command: |
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            eport AWS_DEFAULT_REGION=${{ env.AWS_REGION }}
            sudo docker pull 616864133429.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPO }}:${{ env.TAG  }}
            sudo docker rm -f web_app || true
            sudo docker run --name web_app -p 80:80 -d web:${{env.TAG }}
