name: Push Docker Image on Code Change

on: 
  push:
    branches:
      - main
    paths:
      - src/**
    

env:
  AWS_REGION: us-east-1
  ECR_REPO: node_app

jobs: 
  push:
    name: Push docker image   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Authenticate to AWS 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION  }}

      - name: Authenticate to ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 616864133429.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Generate docker image tag
        run: echo "TAG=${{ github.run_id }}.${{ github.run_number }}.${{ github.retention_days  }}" >> $GITHUB_ENV

      - name: build docker image
        run: docker build -t web:${{ env.TAG }} .

      - name: Tag docker image
        run: docker tag  web:${{env.TAG }} 616864133429.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPO }}:${{ env.TAG  }}

      - name: Push docker image to ECR
        run: docker push 616864133429.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPO }}:${{ env.TAG  }}
